name: All Specs
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DISPLAY: ':99' # For chromedriver
    name: RSpec and Cucumbr
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - rspec
          - cucumber
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/checkout@v2
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ruby -e 'puts ENV.to_h.sort'
      - run: |
          ruby -e 'puts "Key X#{ENV["RAILS_MASTER_KEY"]} |||"'
      - run: npm install -g yarn@1.22.4
      - run: yarn install
      - run: bundle exec rake db:setup
      - run: bundle exec rake db:test:prepare
      - run: bin/rails r 'puts Rails.application.credentials.config.to_h'
      - name: Run ${{ matrix.suite }} Tests
        run: bundle exec ${{ matrix.suite }}
      - name: Report Code Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov/ruby-simplecov.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: kzkn/simplecov-resultset-diff-action@v1
        with:
          base-resultset-path: './coverage/coverage.json'
          head-resultset-path: './coverage/coverage.json'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: head-result
          path: coverage/*
